apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: grafana-stack
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9093"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: grafana-stack-sa
      securityContext:
        fsGroup: 65534
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.27.0
        args:
          - --config.file=/etc/alertmanager/alertmanager.yml
          - --storage.path=/alertmanager
          - --web.external-url=http://localhost:9093
          - --web.listen-address=0.0.0.0:9093
          - --cluster.listen-address=0.0.0.0:9094
          - --log.level=info
          - --log.format=logfmt
        ports:
        - containerPort: 9093
          name: web
          protocol: TCP
        - containerPort: 9094
          name: cluster
          protocol: TCP
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: config
          mountPath: /etc/alertmanager
        - name: storage
          mountPath: /alertmanager
        # templates volume mount removed - using inline templates
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: web
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /-/ready
            port: web
          initialDelaySeconds: 30
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
      volumes:
      - name: config
        configMap:
          name: alertmanager-config
      - name: storage
        emptyDir: {}
      # templates volume removed - using inline templates
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: grafana-stack
  labels:
    app: alertmanager
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9093"
spec:
  type: ClusterIP
  ports:
    - port: 9093
      protocol: TCP
      name: web
      targetPort: web
    - port: 9094
      protocol: TCP
      name: cluster
      targetPort: cluster
  selector:
    app: alertmanager
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-lb
  namespace: grafana-stack
  labels:
    app: alertmanager
spec:
  type: LoadBalancer
  ports:
    - port: 9093
      protocol: TCP
      name: web
      targetPort: web
  selector:
    app: alertmanager
