apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: grafana-stack
data:
  loki.yaml: |
    auth_enabled: false
    
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
      log_level: info
    
    common:
      path_prefix: /tmp/loki
      storage:
        gcs:
          bucket_name: maplequad-11859276-cmf-dev-grafana-stack-b9018bed
          # 使用 Workload Identity，无需 service_account 字段
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
    
    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100
    
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: gcs
          schema: v11
          index:
            prefix: index_
            period: 24h
    
    ruler:
      alertmanager_url: http://alertmanager.grafana-stack.svc.cluster.local:9093
    
    # 禁用使用统计报告（可选）
    analytics:
      reporting_enabled: false
