apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  namespace: grafana-stack
  labels:
    app: mimir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      serviceAccountName: grafana-stack-sa  # 使用配置了 Workload Identity 的 SA
      containers:
      - name: mimir
        image: grafana/mimir:2.10.0
        args:
          - -config.file=/etc/mimir/mimir.yaml
          - -target=all
        ports:
        - containerPort: 8080
          name: http-metrics
        # 使用 Workload Identity，无需设置环境变量
        # GCS bucket 名称直接在 mimir.yaml 配置文件中指定
        volumeMounts:
        - name: config
          mountPath: /etc/mimir
        - name: storage
          mountPath: /tmp/mimir
        # 移除 gcs-credentials volume mount
        livenessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 512Mi
      volumes:
      - name: config
        configMap:
          name: mimir-config
      - name: storage
        emptyDir: {}
      # 移除 gcs-credentials volume
---
apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: grafana-stack
  labels:
    app: mimir
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: mimir
