apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  namespace: grafana-stack
  labels:
    app: mimir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      serviceAccountName: grafana-stack-sa
      containers:
      - name: mimir
        image: grafana/mimir:2.10.0
        args:
          - -config.file=/etc/mimir/mimir.yaml
          - -target=all
        ports:
        - containerPort: 8080
          name: http-metrics
        env:
        - name: GCS_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: gcs-config
              key: bucket-name
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/gcs/service-account-key.json
        volumeMounts:
        - name: config
          mountPath: /etc/mimir
        - name: gcs-credentials
          mountPath: /etc/gcs
          readOnly: true
        - name: storage
          mountPath: /tmp/mimir
        livenessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 512Mi
      volumes:
      - name: config
        configMap:
          name: mimir-config
      - name: gcs-credentials
        secret:
          secretName: gcs-credentials
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: grafana-stack
  labels:
    app: mimir
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: mimir
