apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
  namespace: grafana-stack
data:
  mimir.yaml: |
    # Disable the requirement that every request to Mimir has a
    # X-Scope-OrgID header. `anonymous` will be substituted in instead.
    multitenancy_enabled: false
    
    # Configure the server
    server:
      http_listen_port: 8080
      log_level: info
      # 启用remote write接口
      grpc_listen_port: 9095
    
    # Configure the distributor
    distributor:
      pool:
        health_check_ingesters: true
      ring:
        kvstore:
          store: inmemory
    
    # Configure validation limits
    limits:
      max_label_names_per_series: 50
      max_label_name_length: 1024
      max_label_value_length: 4096
      max_metadata_length: 1024
      ingestion_rate: 50000
      ingestion_burst_size: 100000
      max_global_series_per_user: 150000
      max_global_series_per_metric: 20000
    
    # Configure the ingester
    ingester:
      ring:
        final_sleep: 0s
        num_tokens: 512
        tokens_file_path: /tmp/tokens
        unregister_on_shutdown: false
        zone_awareness_enabled: false
        replication_factor: 1
        kvstore:
          store: inmemory
    
    # Configure storage (using GCS bucket for production-ready storage)
    blocks_storage:
      backend: gcs
      gcs:
        bucket_name: "maplequad-11859276-cmf-dev-grafana-stack-b9018bed"
        service_account: /etc/gcs/service-account-key.json
      tsdb:
        dir: /tmp/mimir/tsdb
        retention_period: 24h
    
    alertmanager_storage:
      backend: gcs
      gcs:
        bucket_name: "maplequad-11859276-cmf-dev-grafana-stack-b9018bed"
        prefix: alertmanager/
        service_account: /etc/gcs/service-account-key.json
    
    ruler_storage:
      backend: gcs
      gcs:
        bucket_name: "maplequad-11859276-cmf-dev-grafana-stack-b9018bed"
        prefix: ruler/
        service_account: /etc/gcs/service-account-key.json
    
    # Configure the store-gateway
    store_gateway:
      sharding_ring:
        kvstore:
          store: inmemory
    
    # Configure the compactor
    compactor:
      data_dir: /tmp/mimir/compactor
      sharding_ring:
        kvstore:
          store: inmemory
