apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-stack-sa
  namespace: grafana-stack
  annotations:
    iam.gke.io/gcp-service-account: grafana-stack@${PROJECT_ID}.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-stack-role
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-stack-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-stack-role
subjects:
- kind: ServiceAccount
  name: grafana-stack-sa
  namespace: grafana-stack 