apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: grafana-stack
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      serviceAccountName: grafana-stack-sa
      containers:
      - name: tempo
        image: grafana/tempo:2.2.0
        args:
          - -config.file=/etc/tempo/tempo.yaml
        ports:
        - containerPort: 3200
          name: http
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        - containerPort: 14250
          name: jaeger-grpc
        - containerPort: 14268
          name: jaeger-http
        - containerPort: 9411
          name: zipkin
        - containerPort: 6831
          name: jaeger-compact
        - containerPort: 6832
          name: jaeger-binary
        - containerPort: 55678
          name: opencensus
        env:
        - name: GCS_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: gcs-config
              key: bucket-name
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/service-account-key.json
        volumeMounts:
        - name: config
          mountPath: /etc/tempo
        - name: gcs-credentials
          mountPath: /var/secrets/google
          readOnly: true
        - name: storage
          mountPath: /tmp/tempo
        livenessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 45
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 45
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
      volumes:
      - name: config
        configMap:
          name: tempo-config
      - name: gcs-credentials
        secret:
          secretName: gcs-credentials
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: grafana-stack
  labels:
    app: tempo
spec:
  type: ClusterIP
  ports:
    - port: 3200
      protocol: TCP
      name: http
      targetPort: http
    - port: 4317
      protocol: TCP
      name: otlp-grpc
      targetPort: otlp-grpc
    - port: 4318
      protocol: TCP
      name: otlp-http
      targetPort: otlp-http
    - port: 14250
      protocol: TCP
      name: jaeger-grpc
      targetPort: jaeger-grpc
    - port: 14268
      protocol: TCP
      name: jaeger-http
      targetPort: jaeger-http
    - port: 9411
      protocol: TCP
      name: zipkin
      targetPort: zipkin
    - port: 6831
      protocol: UDP
      name: jaeger-compact
      targetPort: jaeger-compact
    - port: 6832
      protocol: UDP
      name: jaeger-binary
      targetPort: jaeger-binary
    - port: 55678
      protocol: TCP
      name: opencensus
      targetPort: opencensus
  selector:
    app: tempo 