apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: grafana-stack
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200
      log_level: info
    
    distributor:
      receivers:
        jaeger:
          protocols:
            thrift_http:
              endpoint: 0.0.0.0:14268
            grpc:
              endpoint: 0.0.0.0:14250
            thrift_binary:
              endpoint: 0.0.0.0:6832
            thrift_compact:
              endpoint: 0.0.0.0:6831
        zipkin:
          endpoint: 0.0.0.0:9411
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318
            grpc:
              endpoint: 0.0.0.0:4317
        opencensus:
          endpoint: 0.0.0.0:55678
    
    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1_000_000
      max_block_duration: 5m
    
    compactor:
      compaction:
        compaction_window: 1h
        max_block_bytes: 100_000_000
        block_retention: 1h
        compacted_block_retention: 10m
    
    storage:
      trace:
        backend: gcs
        gcs:
          bucket_name: maplequad-11859276-cmf-dev-grafana-stack-b9018bed
          # 使用 Workload Identity，无需 service_account 字段
        wal:
          path: /tmp/tempo/wal
        local:
          path: /tmp/tempo/blocks
        pool:
          max_workers: 100
          queue_depth: 10000
